#include <letter_writing.h>

#include <main.h>
#include <motors_processing.h>

#define WHEEL_DISTANCE      5.35f    //cm
#define PERIMETER_EPUCK     (PI * WHEEL_DISTANCE)

#define VITESSE_ECRITURE	30

//distance (en cm) en ligne à parcourir principalement basée sur la première de 30cm
#define DISTANCE_HAUTEUR			30
#define DEUX_TIERS_DE_DISTANCE		20
#define MOITIE_DISTANCE				15
#define TIER_DE_DISTANCE			10
#define SIXIEME_DE_DISTANCE			5
#define BARRE_LATERALE_LETTRE_A		40
#define BARRE_CENTRALE_LETTRE_N		32
#define COURBE_LETTRE_D				14.14

//distance (en cm) à parcourir pour réaliser une rotation
#define DEMI_TOUR				PERIMETER_EPUCK/2
#define TIER_DE_TOUR			PERIMETER_EPUCK/3
#define QUART_DE_TOUR			PERIMETER_EPUCK/4
#define SIXIEME_DE_TOUR			PERIMETER_EPUCK/6
#define HUITIEME_DE_TOUR		PERIMETER_EPUCK/8
#define ROTATION_160_DEGRE		4*PERIMETER_EPUCK/9
#define ROTATION_140_DEGRE		7*PERIMETER_EPUCK/18
#define ROTATION_110_DEGRE		11*PERIMETER_EPUCK/36
#define ROTATION_20_DEGRE		PERIMETER_EPUCK/18

void decalage_interlettre(void){
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);		//rotation
	motors_set_position(MOITIE_DISTANCE, MOITIE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);	//ligne							//ligne
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, -VITESSE_ECRITURE, VITESSE_ECRITURE);
}

void lettre_M (void){
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
    motors_set_position(TIER_DE_TOUR, TIER_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
    motors_set_position(MOITIE_DISTANCE, MOITIE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
    motors_set_position(SIXIEME_DE_TOUR, SIXIEME_DE_TOUR, -VITESSE_ECRITURE, VITESSE_ECRITURE);
    motors_set_position(MOITIE_DISTANCE, MOITIE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
    motors_set_position(TIER_DE_TOUR, TIER_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
    motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
    //dernière rotation pour un retour à l'orientation intiale
    motors_set_position(DEMI_TOUR, DEMI_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
}

void lettre_O(void){
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, -VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(TIER_DE_DISTANCE, TIER_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DEUX_TIERS_DE_DISTANCE, DEUX_TIERS_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(TIER_DE_DISTANCE, TIER_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
}

void lettre_N(void){
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_160_DEGRE, ROTATION_160_DEGRE, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(BARRE_CENTRALE_LETTRE_N, BARRE_CENTRALE_LETTRE_N, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_160_DEGRE, ROTATION_160_DEGRE, -VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(DEMI_TOUR, DEMI_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(DEMI_TOUR, DEMI_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
}

void lettre_D(void){
	motors_set_position(DISTANCE_HAUTEUR, DISTANCE_HAUTEUR, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(SIXIEME_DE_DISTANCE, SIXIEME_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(HUITIEME_DE_TOUR, HUITIEME_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(COURBE_LETTRE_D, COURBE_LETTRE_D, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(HUITIEME_DE_TOUR, HUITIEME_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(TIER_DE_DISTANCE, TIER_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(HUITIEME_DE_TOUR, HUITIEME_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(COURBE_LETTRE_D, COURBE_LETTRE_D, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(HUITIEME_DE_TOUR, HUITIEME_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(SIXIEME_DE_DISTANCE, SIXIEME_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(QUART_DE_TOUR, QUART_DE_TOUR, VITESSE_ECRITURE, -VITESSE_ECRITURE);
}

void lettre_A(void){
	motors_set_position(ROTATION_20_DEGRE, ROTATION_20_DEGRE, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(BARRE_LATERALE_LETTRE_A, BARRE_LATERALE_LETTRE_A, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_140_DEGRE, ROTATION_140_DEGRE, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DEUX_TIERS_DE_DISTANCE, DEUX_TIERS_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_110_DEGRE, ROTATION_110_DEGRE, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DEUX_TIERS_DE_DISTANCE, DEUX_TIERS_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_110_DEGRE, ROTATION_110_DEGRE, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(DEUX_TIERS_DE_DISTANCE, DEUX_TIERS_DE_DISTANCE, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_140_DEGRE, ROTATION_140_DEGRE, VITESSE_ECRITURE, -VITESSE_ECRITURE);
	motors_set_position(BARRE_LATERALE_LETTRE_A, BARRE_LATERALE_LETTRE_A, VITESSE_ECRITURE, VITESSE_ECRITURE);
	motors_set_position(ROTATION_160_DEGRE, ROTATION_160_DEGRE, -VITESSE_ECRITURE, VITESSE_ECRITURE);
}
